---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Copy the file
      copy:
        src: /tmp/tempfile
        dest: /tmp
        owner: user
        group: root
        mode: 0777
        